### ISSUE TITLE
Why this repo has no tags?

### ISSUE THREAD

**Issue by qrilka** [antirez/redis-doc#690]
It would be much easier to check how redis commands were changing in history if there were version tags, then it would be possible e.g. to compare commands in version 2.6 vs 3.2

**Comment by badboy** [comment]
Because the documentation in this repository does not evolve in complete lock-step with the main repo. Therefore it is hard to pin a certain point to a specific version of the main project.

We try to mark changes to commands with the respective version. If we fail to do so I'll encourage you to report it and we will do our best to fix it.
In general, certain things of commands will be stable across versions. For example the return value of commands should not change in newer versions (if they ever change we need to document that)
